feature / REL-1199 / Complex Search
oat-sa/generis pull request #1060
Opened 2023-08-17 15:49 UTC by vbyndych

2023-08-21 09:22 UTC, augustas requested changes

2023-08-21 11:56 UTC, vbyndych commented on core/kernel/persistence/starsql/search/Command/Condition.php
> +    public function __construct(BooleanType $condition, array $parameterList = [])
Yes, I know, but if you check this interface it contains `and`, `or`, `not` methods which we need. Also, all the different objects which we will use have this type, so it is what it is.

2023-08-21 11:59 UTC, vbyndych commented on core/kernel/persistence/starsql/search/QuerySerializer.php
> +                    ->withVariable(Query::variable('grandParent'));
I can but both parent and grandparent are ancestors, so the variable name here indicates we are going to look further than parent class.

2023-09-04 12:10 UTC, augustas approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-09-05 09:55 UTC, merged