Added check to ensure file is writeable before updating.
oat-sa/generis pull request #700
Opened 2019-11-08 15:37 UTC by martijn-tao

2019-11-08 15:44 UTC, siwane commented on common/oatbox/filesystem/utils/FileSystemWrapperTrait.php
> +        return is_writable($this->getFullPath($path));
Does it work with remote storage?

2019-11-08 15:55 UTC, julien-sebire requested changes
Hi Martĳn, do you think we can have some tests?

2019-11-08 15:55 UTC, julien-sebire commented on common/oatbox/filesystem/utils/FileSystemWrapperTrait.php
> +        return is_writable($this->getFullPath($path));
Not existing in FlySystem... :(

2019-11-11 08:46 UTC, peetya commented on common/oatbox/filesystem/File.php
> +            throw new FileNotWritableException(sprintf('Unable to write to file "%s"', $this->getPrefix()));
Missing test.

2019-11-13 15:24 UTC, closed without merging