Feature/phpunit 7 ugrade
oat-sa/generis pull request #735
Opened 2020-02-17 09:17 UTC by mike-ionut-mihai-sandu-tao

Updated phpunit to version 7.0.3
tested on : PHP 7.2.24 (cli) (built: Oct 25 2019 04:29:43)

2020-02-19 13:30 UTC, julien-sebire requested changes
I'm not sure this is coordinated with what @shpran already did on this spike. Please synchronize with him...

2020-02-19 13:30 UTC, julien-sebire commented on composer.json
> +    "phpunit/phpunit": "7.0.*",
The plan is to put all this in a separate library, right?

2020-02-19 13:30 UTC, julien-sebire commented on test/PHPUnit_Framework_ExpectationFailedException.php
> +}
Missing line feed at end of file.

2020-02-19 13:30 UTC, julien-sebire commented on test/PHPUnit_Framework_ExpectationFailedException.php
> +class PHPUnit_Framework_ExpectationFailedException extends ExpectationFailedException
Why creating a new class with this kind of non-namespaced name?

2020-02-19 13:30 UTC, julien-sebire commented on test/TestCase.php
> +     * backward compatibility function for PHPUnit 4.0
We're supposed to be in phpunit version 5.7, right?

2020-03-12 11:07 UTC, Yury-Razhkou commented on test/TestCase.php
> +    public function setExpectedException($exception)
4.8.36 :
```
    public function setExpectedException($exceptionName, $exceptionMessage = '', $exceptionCode = null)
{
        $this->expectedException        = $exceptionName;
        $this->expectedExceptionMessage = $exceptionMessage;
        $this->expectedExceptionCode    = $exceptionCode;
    }
```
To keep messages we can adopt this to:
```
public function setExpectedException(string $exception,strin $message='',string $code = '')
    {
        $this->expectException($exception);
        if($message){
        	$this->expectExceptionMessage($message);
        }
        if($code){
        	$this->expectExceptionCode($code);
        }
    }
```

2020-03-17 14:11 UTC, closed without merging