Fix/tao 10423 label not indexed in memory queue
oat-sa/generis pull request #826
Opened 2020-08-20 08:48 UTC by andreluizmachado

This PR is intended to fix the issues:
https://oat-sa.atlassian.net/browse/TAO-10423
https://oat-sa.atlassian.net/browse/TAO-10318

**The problem**
Tao platforms are sending duplicate ResourceUpdate events. This is because, in most cases, resources are not changed in a transaction, but in small blocks. The result of this is a storm of duplicate events.

**The solution**
We will aggregate only single events and trigger them when we reach the maximum number of aggregated events or when the application is shutting down (check: https://github.com/oat-sa/tao-core/pull/2646 for more details).

2020-08-21 06:43 UTC, luisfn requested changes
Seems pretty good to me, would just expect a review from someone with more experience on tao
Aside from that, have added just a couple questions

2020-08-21 06:43 UTC, luisfn commented on core/kernel/classes/class.Resource.php
> +        return $this->getUri() == $resource->getUri();
Maybe use `===`?

2020-08-21 06:43 UTC, luisfn commented on manifest.php
> +    'version' => '13.1.1',
Until now we were not updating versions and it probably will be outdated until merge to develop/master so I'm not sure we should update now

2020-08-21 06:43 UTC, luisfn commented on migrations/Version202008201138552348_generis.php
> +              'numberOfAggregatedEvents' => 10
Maybe call it maxAggregatedEvent? the current name is fine as well, if you think it's better just keep it

2020-08-21 06:43 UTC, luisfn commented on test/OntologyMockTrait.php
> +        $eventAggregator->setServiceLocator($sl);
I know the name was already there, but would rename `$sl` and `$pm` to meaningful names

2020-08-21 06:43 UTC, luisfn commented on test/unit/oatbox/event/EventAggregatorTest.php
> +    public function testTriggerEventsWhenNumberOfAggregatedEventsRichesTheMaximum(): void
Reaches

2020-08-21 06:43 UTC, luisfn commented on test/unit/oatbox/event/EventAggregatorTest.php
> +    public function testTriggerAggregatedEvents(): void
Here you are triggering even if the maximum was not reached? Like forcing?
If yes, maybe you should rename the test

2020-08-24 06:21 UTC, andreluizmachado commented on common/oatbox/event/EventAggregator.php
> +    public function put(string $eventId, Event $event): void
I thought about it and the problem is that would impact all the events which is a big risk IMO.

2020-08-24 10:55 UTC, Skyld approved these changes
- [x] New code is covered by tests
- [ ] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues
- [ ] Feature is working correctly on my local machine
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes

2020-08-24 13:20 UTC, merged