feat! :moved to own lib
oat-sa/generis pull request #858
Opened 2021-01-03 18:07 UTC by boajer

https://oat-sa.atlassian.net/browse/CON-287

https://github.com/oat-sa/lib-generis-gcp/pull/4

Sample configuration
```
 'gcs' => [
                'class' => '\oat\Gcp\Gcs\GcsFlyWrapper',
                'options' => [
                    [
                        'cache'=>'/var/www/html/data/gcp_cache',
                        'bucket' => 'construct',
                        'clientConfig' => [
                            'keyFilePath' => '/var/www/html/constructor.json'
                        ]
                    ]
                ]
```

2021-01-05 12:06 UTC, shpran approved these changes

2021-01-05 14:20 UTC, gabrielfs7 commented on common/oatbox/filesystem/wrapper/GoogleStorageWrapper.php
> -class GoogleStorageWrapper extends ConfigurableService implements AdapterInterface
Do you think this is a breaking change? Maybe we should @deprecate this class / methods and point to the library instead?

2021-01-05 14:20 UTC, gabrielfs7 requested changes
Good job!

Missing update manifest.php

If possible, we should try to avoid the breaking change with deprecation.

2021-01-05 14:21 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-01-13 12:37 UTC, gabrielfs7 approved these changes

2021-01-25 13:17 UTC, merged